# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fscore',
                'doc_host': 'https://Fewsats.github.io',
                'git_url': 'https://github.com/Fewsats/fscore',
                'lib_path': 'fscore'},
  'syms': { 'fscore.queue': { 'fscore.queue.TaskQueue': ('queue.html#taskqueue', 'fscore/queue.py'),
                              'fscore.queue.TaskQueue.__init__': ('queue.html#taskqueue.__init__', 'fscore/queue.py'),
                              'fscore.queue.TaskQueue._guarded_execute': ('queue.html#taskqueue._guarded_execute', 'fscore/queue.py'),
                              'fscore.queue.TaskQueue.enqueue': ('queue.html#taskqueue.enqueue', 'fscore/queue.py'),
                              'fscore.queue.TaskQueue.start': ('queue.html#taskqueue.start', 'fscore/queue.py')}}}
